import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

const appDir = join(process.cwd(), "src/app");
const source = (path: string) => readFileSync(join(appDir, path), "utf8");
const filesUnder = (dir: string): string[] =>
  readdirSync(dir).flatMap((entry) => {
    const fullPath = join(dir, entry);
    return statSync(fullPath).isDirectory() ? filesUnder(fullPath) : [fullPath];
  });

describe("public account routing policy", () => {
  it("keeps the root page public instead of redirecting visitors to /home", () => {
    const rootPage = source("(marketing)/page.tsx");

    expect(rootPage).not.toContain('redirect("/home")');
    expect(rootPage).toContain("MarketingHome");
  });

  it("defines a marketing route shell for public pages", () => {
    const marketingLayout = source("(marketing)/layout.tsx");
    const marketingHome = source("(marketing)/MarketingHome.tsx");

    expect(marketingLayout).toContain("children");
    expect(marketingLayout).toContain("MarketingHeader");
    expect(marketingLayout).toContain("MarketingFooter");
    expect(marketingHome).toContain("Một nơi an toàn để lưu trữ");
    expect(marketingHome).toContain("Cách HealthLens hoạt động");
    expect(marketingHome).toContain("LandingGuestCtas");
    expect(marketingHome).toContain("LandingDashboardPreview");
    expect(marketingHome).not.toContain("LandingGuestClosingBand");
  });

  it("keeps app metadata Vietnamese and removes Create Next App defaults", () => {
    const rootLayout = source("layout.tsx");

    expect(rootLayout).toContain('lang="vi"');
    expect(rootLayout).not.toContain("Create Next App");
    expect(rootLayout).not.toContain("Generated by create next app");
  });

  it("hides consent modal on public marketing routes", () => {
    const consentModal = readFileSync(
      join(process.cwd(), "src/components/features/consent/ConsentModal.tsx"),
      "utf8",
    );

    expect(consentModal).toContain('"/"');
    expect(consentModal).toContain('"/privacy"');
    expect(consentModal).toContain('"/terms"');
    expect(consentModal).toContain('"/help"');
    expect(consentModal).toContain('"/support"');
    expect(consentModal).toContain('"/faq"');
    expect(consentModal).toContain('"/questions"');
  });

  it("keeps auth homepage links pointed at the public root", () => {
    const authSources = filesUnder(join(appDir, "(auth)"))
      .filter((path) => path.endsWith(".tsx"))
      .map((path) => readFileSync(path, "utf8"));

    const homeLinkSources = authSources.filter((content) =>
      content.includes("Quay lại trang chủ"),
    );

    expect(homeLinkSources.length).toBeGreaterThan(0);
    for (const content of homeLinkSources) {
      expect(content).toContain('href="/"');
      expect(content).not.toContain('href="/home"');
    }
  });
});
