#!/usr/bin/env node
import { access, mkdir, rm, writeFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const DEFAULT_INPUT = "http://localhost:8080/v3/api-docs";
const DEFAULT_OUTPUT = "packages/shared/generated/openapi";
const DEFAULT_CONFIG = "scripts/openapi/openapi-generator.config.yaml";
const ALLOWED_OUTPUT = "packages/shared/generated/openapi";
const MODEL_ONLY_GLOBAL_PROPERTY = "models,supportingFiles=index.ts,modelDocs=false,modelTests=false";
const MODEL_ONLY_BARREL = `/* tslint:disable */
/* eslint-disable */
// Generated by scripts/openapi/generate.mjs. Do not edit by hand.
export * from './models/index';
`;

export function parseArgs(argv, env = process.env) {
  const options = {
    input: env.OPENAPI_INPUT || DEFAULT_INPUT,
    output: env.OPENAPI_OUTPUT || DEFAULT_OUTPUT,
    config: env.OPENAPI_CONFIG || DEFAULT_CONFIG,
    dryRun: false,
    skipClean: false,
    help: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const nextValue = () => {
      const value = argv[index + 1];
      if (!value || value.startsWith("-")) {
        throw new Error(`Missing value for ${arg}`);
      }
      index += 1;
      return value;
    };

    if (arg === "-i" || arg === "--input") {
      options.input = nextValue();
    } else if (arg.startsWith("--input=")) {
      options.input = arg.slice("--input=".length);
    } else if (arg === "-o" || arg === "--output") {
      options.output = nextValue();
    } else if (arg.startsWith("--output=")) {
      options.output = arg.slice("--output=".length);
    } else if (arg === "-c" || arg === "--config") {
      options.config = nextValue();
    } else if (arg.startsWith("--config=")) {
      options.config = arg.slice("--config=".length);
    } else if (arg === "--dry-run") {
      options.dryRun = true;
    } else if (arg === "--skip-clean") {
      options.skipClean = true;
    } else if (arg === "-h" || arg === "--help") {
      options.help = true;
    } else {
      throw new Error(`Unknown option: ${arg}`);
    }
  }

  return options;
}

export function usage() {
  return `Usage: pnpm openapi:generate [--input <url-or-file>] [--output <dir>] [--config <file>] [--dry-run] [--skip-clean]

Defaults:
  --input   ${DEFAULT_INPUT}
  --output  ${DEFAULT_OUTPUT}
  --config  ${DEFAULT_CONFIG}

Environment overrides:
  OPENAPI_INPUT, OPENAPI_OUTPUT, OPENAPI_CONFIG

Examples:
  pnpm openapi:generate
  pnpm openapi:generate --input ./tmp/openapi.json
  OPENAPI_INPUT=http://localhost:8080/v3/api-docs pnpm openapi:generate
`;
}

export function isHttpUrl(value) {
  return value.startsWith("http://") || value.startsWith("https://");
}

export async function verifyInput(input) {
  if (isHttpUrl(input)) {
    let response;
    try {
      response = await fetch(input, {
        headers: { accept: "application/json" },
      });
    } catch (error) {
      throw new Error(
        `OpenAPI source is not reachable: ${input}\nStart the API locally or pass --input ./path/to/openapi.json.\nCause: ${error.message}`,
      );
    }

    if (!response.ok) {
      throw new Error(`OpenAPI source returned HTTP ${response.status}: ${input}`);
    }

    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("json")) {
      console.warn(`Warning: OpenAPI source did not advertise JSON content-type: ${contentType || "(none)"}`);
    }
    await response.arrayBuffer();
    return;
  }

  try {
    await access(path.resolve(input), fsConstants.R_OK);
  } catch {
    throw new Error(`OpenAPI source file is not readable: ${input}`);
  }
}

export function buildGeneratorArgs(options) {
  const args = [
    "exec",
    "openapi-generator-cli",
    "generate",
    "--input-spec",
    options.input,
    "--output",
    options.output,
    "--config",
    options.config,
    "--global-property",
    MODEL_ONLY_GLOBAL_PROPERTY,
    "--minimal-update",
  ];

  if (options.dryRun) {
    args.push("--dry-run");
  }

  return args;
}

export async function writeModelOnlyBarrel(outputPath) {
  await writeFile(path.join(outputPath, "index.ts"), MODEL_ONLY_BARREL, "utf8");
}

export async function runGenerator(options, repoRoot = process.cwd()) {
  const outputPath = path.resolve(repoRoot, options.output);
  const allowedOutputPath = path.resolve(repoRoot, ALLOWED_OUTPUT);

  await verifyInput(options.input);
  await access(path.resolve(repoRoot, options.config), fsConstants.R_OK);

  if (outputPath !== allowedOutputPath) {
    throw new Error(`OpenAPI output must remain ${ALLOWED_OUTPUT}; received ${options.output}`);
  }

  if (!options.dryRun && !options.skipClean) {
    await rm(outputPath, { recursive: true, force: true });
  }
  await mkdir(outputPath, { recursive: true });

  const args = buildGeneratorArgs(options);
  await new Promise((resolve, reject) => {
    const child = spawn("pnpm", args, {
      cwd: repoRoot,
      stdio: "inherit",
      shell: process.platform === "win32",
    });

    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`OpenAPI generation failed with exit code ${code}`));
      }
    });
  });

  if (!options.dryRun) {
    await writeModelOnlyBarrel(outputPath);
  }
}

async function main() {
  const options = parseArgs(process.argv.slice(2));

  if (options.help) {
    console.log(usage());
    return;
  }

  await runGenerator(options);
}

const entrypoint = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (entrypoint === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
