generatorName: typescript-fetch
additionalProperties:
  enumPropertyNaming: original
  modelPropertyNaming: original
  stringEnums: true
  supportsES6: true
  useSingleRequestParameter: true
  withoutRuntimeChecks: true
