package com.healthlens.api.exception;

public enum ApiErrorCode {
    ACCOUNT_LOCKED("ACCOUNT_LOCKED"),
    RATE_LIMITED("RATE_LIMITED"),
    ACCOUNT_PENDING_DELETION("ACCOUNT_PENDING_DELETION"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    BUSINESS_ERROR("BUSINESS_ERROR"),
    INVALID_STATE("INVALID_STATE"),
    NOT_FOUND("NOT_FOUND"),
    FORBIDDEN("FORBIDDEN"),
    CONSENT_REQUIRED("CONSENT_REQUIRED"),
    PROFILE_ACCESS_REVOKED("PROFILE_ACCESS_REVOKED"),
    DELETION_CANCEL_TOKEN_INVALID("DELETION_CANCEL_TOKEN_INVALID"),
    DATABASE_ERROR("DATABASE_ERROR"),
    BAD_REQUEST("BAD_REQUEST");

    private final String value;

    ApiErrorCode(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }
}
